services:
  app:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    restart: always
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: eu-north-1
      BUCKET_NAME: ${BUCKET_NAME}
      REDDIT_WEB_AGENT: ${REDDIT_WEB_AGENT}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      REDDIT_CLIENT_SECRET: ${REDDIT_CLIENT_SECRET}
      DEBUG: "${DEBUG:-0}"
    networks:
      - panetwork

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    networks:
      - panetwork
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage:rw
configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  postgres_data:

networks:
  panetwork:
    driver: bridge
